name: Auto Pull Request

on:
  push:
    branches-ignore: 
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main  
          title: "Cambios desde ${{ github.ref_name }}"
          body: "Pull request automático para mergear cambios desde ${{ github.ref_name }}"
          labels: "automatic-pr"

      - name: Trigger Auto-Merge Workflow
        if: steps.create-pr.outputs.pull-request-number
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-auto-merge
          client-payload: '{"pr_number": "${{ steps.create-pr.outputs.pull-request-number }}"}'
