name: Auto Pull Request

on:
  push:
    branches: 
      - release/*
      - new-branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main  
          github_token: ${{ secrets.GH_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"

