name: Auto Pull Request

on:
  push:
    branches: 
      - release/*
      - new-branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main  
          github_token: ${{ secrets.GH_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"

      - name: Check Condition
        if: steps.create-pr.outputs.pull-request-number
        run: echo "entra"
        
      - name: Approve Pull Request
        if: steps.create-pr.outputs.pull-request-number
        uses: peter-evans/approve-pull-request@v3  # Updated version
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}

